from datetime import datetime
from io import BytesIO

from fpdf import FPDF

from app.schemas.response import AnalysisResult

_AGENT_LABELS = {
    "hr_agent": ("HR Agent", "ATS & Keywords"),
    "tech_lead_agent": ("Tech Lead Agent", "Technical Depth"),
    "market_analyst_agent": ("Market Analyst", "Market Fit"),
}

_PRIORITY_COLORS = {
    "HIGH":   (239, 68,  68),
    "MEDIUM": (245, 158, 11),
    "LOW":    (16,  185, 129),
}

_PURPLE = (124, 58, 237)
_BLUE   = (59, 130, 246)
_DARK   = (30, 27, 75)
_GRAY   = (107, 114, 128)
_LIGHT  = (249, 246, 255)


def _score_color(score: int) -> tuple[int, int, int]:
    if score >= 75:
        return (16, 185, 129)
    if score >= 50:
        return (245, 158, 11)
    return (239, 68, 68)


def _score_label(score: int) -> str:
    if score >= 80:
        return "Strong Match"
    if score >= 60:
        return "Good Match"
    if score >= 40:
        return "Partial Match"
    return "Needs Work"


class ResumeReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*_GRAY)
        self.cell(0, 6, "ResumeAI - Confidential Analysis Report", align="L")
        self.cell(0, 6, datetime.now().strftime("%B %d, %Y"), align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(220, 210, 255)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*_GRAY)
        self.cell(0, 8, f"Page {self.page_no()} - Generated by ResumeAI", align="C")

    def section_title(self, title: str):
        self.ln(5)
        self.set_fill_color(237, 233, 254)
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*_PURPLE)
        self.cell(0, 7, f"  {title.upper()}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(3)

    def pill_row(self, items: list[str], bg: tuple, fg: tuple):
        if not items:
            return
        self.set_font("Helvetica", "", 8)
        self.set_fill_color(*bg)
        self.set_text_color(*fg)
        x0 = self.l_margin
        self.set_x(x0)
        for item in items:
            w = self.get_string_width(item) + 6
            if self.get_x() + w > self.w - self.r_margin:
                self.ln(6)
                self.set_x(x0)
            self.cell(w, 5, item, fill=True, border=0)
            self.set_x(self.get_x() + 2)
        self.ln(7)

    def score_circle_row(self, scores: list[tuple[str, int, str]]):
        col_w = (self.w - self.l_margin - self.r_margin) / len(scores)
        y_start = self.get_y()
        for label, score, sublabel in scores:
            x = self.get_x()
            r, g, b = _score_color(score)
            self.set_font("Helvetica", "B", 22)
            self.set_text_color(r, g, b)
            self.cell(col_w, 12, str(score), align="C")
            self.set_x(x)
            self.set_y(self.get_y() + 12)
            self.set_font("Helvetica", "B", 9)
            self.set_text_color(*_DARK)
            self.cell(col_w, 5, label, align="C")
            self.set_x(x)
            self.set_y(self.get_y() + 5)
            self.set_font("Helvetica", "", 8)
            self.set_text_color(*_GRAY)
            self.cell(col_w, 4, sublabel, align="C")
            self.set_xy(x + col_w, y_start)
        self.set_y(y_start + 21)
        self.ln(3)

    def priority_list(self, items, col_w: float = 0):
        if col_w == 0:
            col_w = self.w - self.l_margin - self.r_margin
        for item in items:
            r, g, b = _PRIORITY_COLORS.get(item.priority, _PRIORITY_COLORS["LOW"])
            # Priority badge
            self.set_fill_color(r, g, b)
            self.set_text_color(255, 255, 255)
            self.set_font("Helvetica", "B", 7)
            badge_w = self.get_string_width(item.priority) + 4
            self.cell(badge_w, 5, item.priority, fill=True)
            # Text
            self.set_font("Helvetica", "", 9)
            self.set_text_color(*_DARK)
            self.set_x(self.get_x() + 3)
            self.multi_cell(col_w - badge_w - 5, 5, item.text)
            self.ln(1)

    def skills_bars(self, skills: dict[str, int]):
        bar_total = self.w - self.l_margin - self.r_margin
        for name, value in skills.items():
            self.set_font("Helvetica", "", 9)
            self.set_text_color(*_DARK)
            label_w = 30
            self.cell(label_w, 5, name)
            # Bar background
            bar_x = self.get_x()
            bar_y = self.get_y() + 1
            bar_w = bar_total - label_w - 12
            self.set_fill_color(237, 233, 254)
            self.rect(bar_x, bar_y, bar_w, 3, "F")
            # Bar fill
            self.set_fill_color(*_PURPLE)
            self.rect(bar_x, bar_y, bar_w * value / 100, 3, "F")
            # Percent
            self.set_x(bar_x + bar_w + 3)
            self.set_font("Helvetica", "B", 8)
            self.set_text_color(*_PURPLE)
            self.cell(10, 5, f"{value}%", align="R", new_x="LMARGIN", new_y="NEXT")
            self.ln(1)


def generate_report(result: AnalysisResult) -> bytes:
    pdf = ResumeReport(orientation="P", unit="mm", format="A4")
    pdf.set_margins(16, 16, 16)
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # ── TITLE BLOCK ──────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*_DARK)
    pdf.cell(0, 10, "Resume Analysis Report", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*_GRAY)
    pdf.cell(0, 5, "Powered by ResumeAI - AI-Driven Resume & Job Match Analyzer", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # ── SCORE SUMMARY ─────────────────────────────────────────────
    hr_score   = result.agent_feedback.get("hr_agent", type("_", (), {"score": 0})()).score  # type: ignore[call-arg]
    tech_score = result.agent_feedback.get("tech_lead_agent", type("_", (), {"score": 0})()).score  # type: ignore[call-arg]
    mkt_score  = result.agent_feedback.get("market_analyst_agent", type("_", (), {"score": 0})()).score  # type: ignore[call-arg]

    pdf.set_fill_color(248, 245, 255)
    pdf.set_draw_color(220, 210, 255)
    y0 = pdf.get_y()
    pdf.rect(pdf.l_margin, y0, pdf.w - pdf.l_margin - pdf.r_margin, 28, "FD")
    pdf.set_xy(pdf.l_margin, y0 + 2)
    pdf.score_circle_row([
        ("Overall Match", result.overall_score, _score_label(result.overall_score)),
        ("ATS Score",     hr_score,              "HR Agent"),
        ("Technical Fit", tech_score,            "Tech Lead"),
        ("Market Fit",    mkt_score,             "Market Analyst"),
    ])

    # ── QUICK STATS ───────────────────────────────────────────────
    qs = result.quick_stats
    pdf.section_title("Quick Stats")
    col_w = (pdf.w - pdf.l_margin - pdf.r_margin) / 2
    stats = [
        ("Total Keywords", str(qs.total_keywords)),
        ("Match Rate",     f"{qs.match_rate}%"),
        ("Experience Gap", qs.experience_gap),
        ("Salary Range",   qs.salary_range),
    ]
    for i, (label, value) in enumerate(stats):
        if i % 2 == 0 and i > 0:
            pdf.ln(1)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*_GRAY)
        pdf.cell(col_w, 5, label)
        if i % 2 == 1:
            pdf.ln(0)
        pdf.set_x(pdf.l_margin + (col_w if i % 2 == 1 else 0))

    # Re-render stats cleanly in a table
    pdf.set_y(pdf.get_y())
    for label, value in stats:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_GRAY)
        pdf.cell(50, 5, label)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*_DARK)
        pdf.cell(0, 5, value, new_x="LMARGIN", new_y="NEXT")

    # ── AGENT FEEDBACK ────────────────────────────────────────────
    pdf.section_title("Agent Feedback")
    for key, feedback in result.agent_feedback.items():
        label, subtitle = _AGENT_LABELS.get(key, (key, ""))
        r, g, b = _score_color(feedback.score)
        pdf.set_fill_color(248, 245, 255)
        pdf.rect(pdf.l_margin, pdf.get_y(), pdf.w - pdf.l_margin - pdf.r_margin, 6, "F")
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*_DARK)
        pdf.cell(110, 6, f"{label}  -  {subtitle}")
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(r, g, b)
        pdf.cell(0, 6, str(feedback.score), align="R", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(*_GRAY)
        pdf.multi_cell(0, 4, feedback.summary)
        if feedback.details:
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(*_DARK)
            for d in feedback.details:
                pdf.set_x(pdf.l_margin + 4)
                pdf.cell(4, 4, "-")
                pdf.multi_cell(pdf.w - pdf.l_margin - pdf.r_margin - 8, 4, d)
        pdf.ln(3)

    # ── STRENGTHS ─────────────────────────────────────────────────
    pdf.section_title("Top Strengths")
    for i, s in enumerate(result.strengths, 1):
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*_PURPLE)
        pdf.cell(6, 5, str(i))
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_DARK)
        pdf.multi_cell(0, 5, s)

    # ── MISSING KEYWORDS ──────────────────────────────────────────
    pdf.section_title("Missing Keywords")
    pdf.pill_row(result.missing_keywords, bg=(254, 226, 226), fg=(185, 28, 28))

    # ── MATCHED KEYWORDS ──────────────────────────────────────────
    pdf.section_title("Matched Keywords")
    pdf.pill_row(result.matched_keywords, bg=(220, 252, 231), fg=(21, 128, 61))

    # ── SKILLS COVERAGE ───────────────────────────────────────────
    if result.skills_coverage:
        pdf.section_title("Skills Coverage")
        pdf.skills_bars(result.skills_coverage)

    # ── PRIORITY IMPROVEMENTS ─────────────────────────────────────
    if result.priority_improvements:
        pdf.section_title("Priority Improvements")
        pdf.priority_list(result.priority_improvements)

    # ── ACTION ITEMS ──────────────────────────────────────────────
    if result.action_items:
        pdf.section_title("Top Action Items")
        pdf.priority_list(result.action_items)

    buf = BytesIO()
    pdf.output(buf)
    return buf.getvalue()
